### PR TITLE
release version

### PR DESCRIPTION
**Pull request by deanvollebregt**
Testing of Murray Princess Next confirms the bug is fixed

### CODE REVIEW

**Review by dwaring — COMMENTED** [review]
Do we also need to update line 13 in composer.json?

**Comment by dwaring** [comment]
Update Changelog version from **Unreleased** to **1.1.0**

**Comment by deanvollebregt** [comment]
> Do we also need to update line 13 in composer.json?

That is a default composer module unrelated to the feeforeviewplugin

**Comment by deanvollebregt** [comment]
> Do we also need to update line 13 in composer.json?
done

**Comment by sam-wan** [comment]
@jmortlock @dwaring 

Is this PR dead?  can we close it out?

**Review by jmortlock — APPROVED** [review]

**Review by sam-wan — APPROVED** [review]

**Pull request merged**
